# Generated by Django 4.0.6 on 2022-07-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
                ('name1', models.CharField(max_length=250)),
                ('des1', models.TextField()),
            ],
        ),
    ]
